### PR TITLE
Fix single string entry

### LINKED ISSUE #37: We currently do not inject our entry code into single-file anonymous entries error
Hi,

Using `"error-overlay-webpack-plugin": "^0.2.0"` and `"webpack": "^4.30.0"`, I got this error:

> Error: We currently do not inject our entry code into single-file anonymous entries.
Please use a multi-main (array) or object-form `entry` setting for now.
    at adjustEntry (PATH\node_modules\error-overlay-webpack-plugin\lib\index.js:56:11)

After removing `error-overlay-webpack-plugin` everything works fine.

### PR DESCRIPTION
**Pull request by bencooper222**
Fixes #37 

Not the most elegant fix but it should work.

### CODE REVIEW

**Comment by neoziro** [comment]
Hello @bencooper222, thanks for the fix! I have to test it before, or maybe someone could check if the fix is correct? Without any review I can't merge it.

**Comment by bencooper222** [comment]
@leonm1 or @cktang88 could you test and review this? It's related to https://github.com/VandyHacks/vaken/issues/94

**Comment by leonm1** [comment]
I re-built the error-overlay-webpack-plugin using the patch from this PR and it worked for my app.
Tested building and intentionally causing an error, the error appeared as expected in the overlay.

**Comment by bencooper222** [comment]
@neoziro good to merge, I think?

**Pull request merged**
