### PR TITLE
fix: Object-based entry does not work

### PR DESCRIPTION
**Pull request by domarmstrong**
I'm not sure if this ever worked, this takes each source string out of the object and passes it back to adjustEntry, which then fails because a string was passed in and throws an error.

```
    Object.keys(entry).forEach((entryName) => {
      entry[entryName] = adjustEntry(entry[entryName], chunkPath)
    })
```

I'm not sure you can return a value from the taps, so you cant change the object into an array which would be the proper fix. So I added a warning to highlight that actually it doesnt work well with object-form entry (but at least it does work now).

### CODE REVIEW

**Comment by neoziro** [comment]
@domarmstrong any update?

**Comment by mohsinulhaq** [comment]
any update on this?

**Comment by gnext-andrese03** [comment]
Any update on this?

**Comment by neoziro** [comment]
No, if someone want to take care of updating the subject, it's welcome.

**Pull request closed without merging**
